
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code. All references to sin-wave table should be made        */
/* with information in this file. This allows only symbolic     */
/* information to be referenced which allows the eTPU code to be*/
/* optimized without effecting the CPU code.                    */
/****************************************************************/
#ifndef _ETPU_MC_SIN_AUTO_H_
#define _ETPU_MC_SIN_AUTO_H_

#define FS_ETPU_MC_SIN_MCSINLUT_OFFSET  0x0008

#endif
